// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWzSPMaDie5GjMYruMY10i4ieyI3QEDSo',
    appId: '1:877005315390:android:944dfaeb8960883c6ee06f',
    messagingSenderId: '877005315390',
    projectId: 'seeya-bd99d',
    storageBucket: 'seeya-bd99d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEWm2M95AUrwadm2wegNVBHlK1HJpnOvc',
    appId: '1:877005315390:ios:0b47f28ebd7e46b76ee06f',
    messagingSenderId: '877005315390',
    projectId: 'seeya-bd99d',
    storageBucket: 'seeya-bd99d.appspot.com',
    androidClientId: '877005315390-sq0df6gc4mi05v081s7blj9cndqe9tbp.apps.googleusercontent.com',
    iosClientId: '877005315390-f4edma2d73rt0o2uq254rksc34kd0ae2.apps.googleusercontent.com',
    iosBundleId: 'com.cherryish.seeya',
  );

}