import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'ko_KR': {

      'toast.unknown_error':'알 수 없는 오류가 발생했습니다. 다시 시도해주세요.',
      'toast.error404':'요청하신 리소스를 찾을 수 없습니다.',
      'toast.error500':'처리중 알 수 없는 에러가 발생하였습니다.',

      'enter_user_info.bottom_button':'완료',
      'enter_user_info.title':'필수 정보 입력',
      'enter_user_info.name':'이름',
      'enter_user_info.name_hint':'이름 입력',
      'enter_user_info.email':'이메일',
      'enter_user_info.email_hint':'이메일 주소',
      'enter_user_info.email_check':'중복확인',
      'enter_user_info.email_check_already':'이미 사용중인 이메일입니다.',
      'enter_user_info.email_check_okay':'사용 가능한 이메일입니다.',
      'enter_user_info.toast.invalid_email':'유효하지 않는 이메일 입니다.',

      'phone_verification.bottom_button_next':'다음',
      'phone_verification.bottom_button_get_code':'인증번호 받기',
      'phone_verification.title':'본인 인증',
      'phone_verification.sub_title':'원활한 서비스 이용을 위해,\n휴대폰 번호를 입력해주세요.',
      'phone_verification.phone':'휴대폰 번호',
      'phone_verification.phone_hint':'-를 제외하고 입력해주세요.',
      'phone_verification.code':'인증 번호',
      'phone_verification.code_hint':'인증 번호 6자리',
      'phone_verification.code_resend':'인증 번호 재전송',
      'phone_verification.toast.recaptcha':'reCAPTCHA 인증에 실패하였습니다.',
      'phone_verification.toast.invalid_phone':'잘못된 전화번호입니다.',
      'phone_verification.toast.quota':'오늘의 인증 요청 제한을 초과했습니다. 나중에 다시 시도해주세요.',
      'phone_verification.toast.error':'인증에 실패했습니다.',
      'phone_verification.toast.invalid_code':'인증번호를 다시 확인해주세요.',
      'phone_verification.toast.code_expired':'인증번호 입력 시간이 만료되었습니다.',
      'phone_verification.toast.code_expired_retry':'인증 시간이 만료되었습니다. 다시 시도해주세요.',
      'phone_verification.toast.too_many':'너무 많은 요청을 보냈습니다. 잠시 후 다시 시도해주세요.',
      'phone_verification.toast.network':'네트워크 연결에 문제가 발생했습니다.',
      'phone_verification.toast.code_short':'인증 번호 6자리를 모두 입력해주세요.',

      'sign_up_finish.bottom_button':'시작하기',
      'sign_up_finish.title':'회원가입이\n성공적으로 완료되었습니다!',
      'sign_up_finish.sub_title':'[@user]님, 반갑습니다!',

      'bottom_nav.home':'홈',
      'bottom_nav.map':'지도',
      'bottom_nav.my_page':'마이페이지',

      'home.detail_dialog_button':'이벤트 내용 보러가기',

      'map.search_hint':'장소명, 이벤트명으로 찾아보세요.',
      'map.event_list_title':'추천 이벤트',
      'map.event_list_empty':'진행중인 이벤트가 없습니다.',
      'map.event_list_item_period':'기간 @start_date - @end_date',
      'map.toast.location_error':'위치를 불러올 수 없습니다. 위치 권한을 확인해 주세요.',

      'map_sort.title':'정렬',
      'map_sort.popular':'인기 순',
      'map_sort.distance':'거리 순',
      'map_sort.unknown':'알 수 없음',

      'search.bar_hint':'장소명, 이벤트명으로 찾아보세요.',
      'search.recent':'최근 검색',
      'search.clear':'전체 지우기',

      'event_detail.price':'인화 금액',
      'event_detail.period':'기간',
      'event_detail.address':'주소',
      'event_detail.address_copy':'주소 복사',
      'event_detail.frame_list_title':'프레임을 선택해주세요.',
      'event_detail.frame_list_empty':'종료된 이벤트입니다.',
      'event_detail.toast.load_fail':'이벤트 정보를 불러오지 못했습니다.',
      'event_detail.toast.copied':'복사되었습니다.',

      'camera.complete':'완료',
      'camera.delete':'삭제',
      'camera.toast.allow_permission':'카메라 권한을 허용해 주세요.',
      'camera.toast.init_error':'카메라를 초기화하는 중 오류가 발생했습니다.',

      'image_crop.button':'자르기',
      'image_crop.toast.size_error':'이미지 크기를 가져오는 중 에러가 발생했습니다.',

      'decorate_frame.title':'프레임 내부 꾸미기',
      'decorate_frame.button':'프린트 하기',
      'decorate_frame.toast.empty_cut':'모든 컷을 채워주세요!',
      'decorate_frame.toast.not_found_user':'사용자 정보를 불러올 수 없습니다.',
      'decorate_frame.toast.all_consumed':'재출력 횟수를 모두 소진하셨습니다.',
      'decorate_frame.toast.cant_user':'현재 이용할 수 없는 상황입니다. 잠시 후에 다시 시도해주세요.',
      'decorate_frame.toast.already_finish':'이미 종료된 이벤트입니다.',
      'decorate_frame.toast.already_printing':'이미 프린트 중입니다.',
      'decorate_frame.toast.merge_error':'이미지를 병합하는중 오류가 발생하였습니다.',

      'decorate_frame_back_dialog.title':'프레임을 삭제하시겠어요?',
      'decorate_frame_back_dialog.description':'지금 돌아가면 변경 사항이 삭제됩니다.',
      'decorate_frame_back_dialog.button01':'삭제하기',
      'decorate_frame_back_dialog.button02':'계속 제작하기',

      'decorate_frame_confirm_dialog.warning':'잠깐!',
      'decorate_frame_confirm_dialog.title':'이 단계 후\n바로 인쇄가 진행됩니다.',
      'decorate_frame_confirm_dialog.description':'프린터가 배치된 장소와 가까이 있어주세요. 지연된 수거에 의해 발생한\n분실은 책임지지 않습니다.',
      'decorate_frame_confirm_dialog.button01':'앞으로 돌아가기',
      'decorate_frame_confirm_dialog.button02':'진행하기',

      'decorate_frame_complete_dialog.title':'등록이 완료 되었습니다!\n대기번호 : @waitCount',
      'decorate_frame_complete_dialog.button01':'내역 확인하기',
      'decorate_frame_complete_dialog.button02':'이벤트 페이지로 가기',

      'loading.overlay01':'이미지를 올바르게 회전 중입니다.',
      'loading.overlay02':'이미지 사이즈를 조절중입니다.',
      'loading.overlay03':'이미지를 합치는 중입니다.',
      'loading.overlay04':'모든 이미지를 병합중입니다..',
      'loading.overlay05':'인쇄 요청중...',

      'share.button':'링크 공유하기',
      'share.toast.event_not_found':'이벤트 정보를 불러오지 못 했습니다.',

      'login.title':'간편 로그인/회원가입',
      'login.button':'@platform로 시작하기',
      'login.toast.exist_email':'이미 가입되어 있는 이메일 주소입니다.',
      'login.toast.withdrawal':'계정이 탈퇴 처리되었습니다. 재가입은 3개월 후에 가능합니다.',
      'login.toast.kakao_error01':'카카오톡 로그인 중 에러 발생하였습니다.',
      'login.toast.kakao_error02':'카카오 계정 정보를 불러올 수 없습니다.',

      'my_page.seeya_user':'[@name]',
      'my_page.no_name_user':'[시야 손님 @user_id]',
      'my_page.login_from':'@platform로 로그인',
      'my_page.seeya_guide_menu':'Seeya 안내',
      'my_page.print_history':'프린트 히스토리',
      'my_page.report':'에러 리포트',
      'my_page.qna_menu':'자주 묻는 질문',
      'my_page.setting':'설정',
      'my_page.logout':'로그아웃',

      'seeya_guide.title':'Seeya 안내',
      'seeya_guide.description':'내 손 안의 포토부스, 시야',
      'seeya_guide.step1_title':'찾고',
      'seeya_guide.step1_description':'특별했던 장소의 프레임을\n\'시야\'에서 찾아보세요!',
      'seeya_guide.step2_title':'찍고',
      'seeya_guide.step2_description':'선택한 프레임에 기억하고 싶은 순간들을\n넣어보세요!',
      'seeya_guide.step3_title':'뽑고',
      'seeya_guide.step3_description':'결제를 마치고 조금만 기다리면\n한장에 담기는 소중한 오늘이 당신 손안에!',

      'print_history.title':'프린트 히스토리',
      'print_history.empty':'히스토리가 존재하지 않습니다.',

      'report.title':'에러 리포트',
      'report.tab_bar_menu1':'이용 내역',
      'report.tab_bar_menu2':'문의 내역',
      'report.item_button01':'에러 리포트하기',
      'report.item_button02':'재출력',
      'report.item_status_completed':'출력 완료',
      'report.item_status_error':'에러',
      'report.item_status_reported':'문의 완료',
      'report.item_status_pending':'출력중',
      'report.item_status_wait':'대기중',

      'report.toast.all_consumed':'재출력 횟수를 모두 소진하셨습니다.',
      'report.toast.cant_use':'현재 이용할 수 없는 상황입니다. 잠시 후에 다시 시도해주세요.',
      'report.toast.already_finish':'이미 종료된 이벤트입니다.',
      'report.toast.already_printing':'이미 프린트 중입니다.',
      'report.toast.fail_load_user':'사용자 정보를 불러올 수 없습니다.',

      'report_reprint_dialog.title':'재출력',
      'report_reprint_dialog.sub_title':'재출력은 1회까지만 가능합니다.',
      'report_reprint_dialog.button01':'취소',
      'report_reprint_dialog.button02':'프린트 하기',

      'inquiry_detail.title':'문의 내역',
      'inquiry_detail.error_reception':'에러 접수',
      'inquiry_detail.in_progress':'진행중',
      'inquiry_detail.status':'진행 상태',
      'inquiry_detail.answer_pending':'진행중입니다. 조금만 기다려주시면 빠르게 진행 도와드리겠습니다.',
      'inquiry_detail.answer_accepted':'@date\n환불처리 완료되었습니다.',
      'inquiry_detail.status_pending':'환불 완료',
      'inquiry_detail.status_pending_with_date':'@date 환불 요청 완료',
      'inquiry_detail.status_accepted':'환불 완료',
      'inquiry_detail.status_accepted_with_date':'@date 환불 완료',
      'inquiry_detail.status_denied':'환불 반려',
      'inquiry_detail.status_denied_with_date':'@date 환불 반려됨',
      'inquiry_detail.status_in_progress':'진행중',

      'inquiry_history.print_complete':'@date 인쇄 완료',

      'usage_history.report':'에러 리포트하기',
      'usage_history.reprint':'재출력',

      'error_report.title':'에러 리포트',
      'error_report.cancel':'취소',
      'error_report.register':'등록',
      'error_report.error_reason_title':'에러가 발생한 상황이나\n프레임의 사진을 첨부해주세요',
      'error_report.upload_photo':'사진 첨부하기',
      'error_report.toast.already_post':'이미 문의가 등록되었습니다.',

      'report_complete_dialog.title':'등록이 완료 되었습니다!\n대기번호 : @waitCount',
      'report_complete_dialog.button01':'확인',

      'qna.title':'자주 묻는 질문',
      'qna.footer':'이외의 문의는\n고객센터 이메일(info@seeya-printer.com)으로\n문의 바랍니다.',

      'withdrawal.title':'회원 탈퇴',
      'withdrawal.sub_title':'회원 탈퇴 주의사항',
      'withdrawal.description01':'진행중 혹은 예약 완료된 이벤트가 있을 경우, 탈퇴가 가능하지 않습니다.',
      'withdrawal.description02':'구매 내역, 프린트 히스토리, 문의 내역 등 서비스 이용 관련 데이터가 영구 삭제 되고, 복구가 불가합니다.',
      'withdrawal.description03':'삭제된 데이터는 재가입 시에도\n연동이 불가합니다.',
      'withdrawal.description04':'완료되지 않은 환불 요청건은 \n집행이 불가합니다.',
      'withdrawal.confirm':'위의 내용을 모두 확인하였습니다.',
      'withdrawal.button':'탈퇴하기',

      'setting.title':'설정',
      'setting.user_info_title':'기본 회원 정보',
      'setting.user_info_name':'이름',
      'setting.user_info_phone':'연락처',
      'setting.user_info_phone_verify':'휴대폰 인증',
      'setting.user_info_email':'이메일',
      'setting.sns_title':'SNS 연결',
      'setting.terms_service':'서비스 이용약관',
      'setting.terms_privacy':'개인정보 처리방침',
      'setting.withdrawal':'회원 탈퇴',

      'block.title':'관리자에 의해 차단되었습니다.',

      'payment.title':'결제가 진행중입니다.\n웹에서 결제를 완료해주세요!',
      'payment.toast.not_enable':'현재 이용할 수 없습니다. 관리자에게 문의해주세요.',

      'maintenance.title':'서비스 점검중입니다.',
      'maintenance.description':'안전한 서비스 제공을 위해\n현재 서비스를 점검하고 있습니다.',

    },

    ////////////////    ////////////////    ////////////////    ////////////////    ////////////////    ////////////////    ////////////////

    'en_US': {
      'toast.unknown_error': 'An unknown error occurred. Please try again.',
      'toast.error404': 'Requested resource not found.',
      'toast.error500': 'An unexpected error occurred during processing.',
      'enter_user_info.bottom_button': 'Done',
      'enter_user_info.title': 'Enter Required Info',
      'enter_user_info.name': 'Name',
      'enter_user_info.name_hint': 'Enter your name',
      'enter_user_info.email': 'Email',
      'enter_user_info.email_hint': 'Email address',
      'enter_user_info.email_check': 'Check',
      'enter_user_info.email_check_already': 'This email is already in use.',
      'enter_user_info.email_check_okay': 'This email is available.',
      'enter_user_info.toast.invalid_email': 'Invalid email address.',
      'phone_verification.bottom_button_next': 'Next',
      'phone_verification.bottom_button_get_code': 'Get Code',
      'phone_verification.title': 'Phone Verification',
      'phone_verification.sub_title': 'To use the service,\nplease enter your phone number.',
      'phone_verification.phone': 'Phone Number',
      'phone_verification.phone_hint': 'Enter without dashes',
      'phone_verification.code': 'Verification Code',
      'phone_verification.code_hint': '6-digit code',
      'phone_verification.code_resend': 'Resend Code',
      'phone_verification.toast.recaptcha': 'reCAPTCHA verification failed.',
      'phone_verification.toast.invalid_phone': 'Invalid phone number.',
      'phone_verification.toast.quota': 'Daily verification limit reached. Please try again later.',
      'phone_verification.toast.error': 'Verification failed.',
      'phone_verification.toast.invalid_code': 'Please check the code again.',
      'phone_verification.toast.code_expired': 'The code has expired.',
      'phone_verification.toast.code_expired_retry': 'Verification expired. Please try again.',
      'phone_verification.toast.too_many': 'Too many requests. Try again shortly.',
      'phone_verification.toast.network': 'Network issue occurred.',
      'phone_verification.toast.code_short': 'Please enter the full 6-digit code.',
      "sign_up_finish.bottom_button": "Get Started",
      "sign_up_finish.title": "Sign-up Completed Successfully!",
      "sign_up_finish.sub_title": "Welcome, [@user]!",
      "bottom_nav.home": "Home",
      "bottom_nav.map": "Map",
      "bottom_nav.my_page": "My Page",
      "home.detail_dialog_button": "View Event Details",
      "map.search_hint": "Search by place or event name",
      "map.event_list_title": "Recommended Events",
      "map.event_list_empty": "No ongoing events available.",
      "map.event_list_item_period": "Dates @start_date - @end_date",
      "map.toast.location_error": "Location access is disabled. Please enable it in settings.",
      "map_sort.title": "Sort",
      "map_sort.popular": "Popular",
      "map_sort.distance": "By Distance",
      "map_sort.unknown": "Unknown",
      "search.bar_hint": "Search by place or event name",
      "search.recent": "Recent Searches",
      "search.clear": "Clear All",
      "event_detail.price": "Price",
      "event_detail.period": "Dates",
      "event_detail.address": "Address",
      "event_detail.address_copy": "Copy Address",
      "event_detail.frame_list_title": "Select a Frame",
      "event_detail.frame_list_empty": "This event has ended.",
      "event_detail.toast.load_fail": "Failed to load event information.",
      "event_detail.toast.copied": "Copied.",
      "camera.complete": "Done",
      "camera.delete": "Delete",
      "camera.toast.allow_permission": "Please allow camera access.",
      "camera.toast.init_error": "An error occurred while initializing the camera.",
      "image_crop.button": "Crop",
      "image_crop.toast.size_error": "Failed to retrieve image size.",
      "decorate_frame.title": "Fill the Frame",
      "decorate_frame.button": "Print",
      "decorate_frame.toast.empty_cut": "Please fill in all sections!",
      "decorate_frame.toast.not_found_user": "Failed to load user information.",
      "decorate_frame.toast.all_consumed": "You\'ve used all your reprint chances.",
      "decorate_frame.toast.cant_user": "Service currently unavailable. Please try again later.",
      "decorate_frame.toast.already_finish": "This event has already ended.",
      "decorate_frame.toast.already_printing": "Already printing.",
      "decorate_frame.toast.merge_error": "An error occurred while merging images.",
      "decorate_frame_back_dialog.title": "Delete the Frame?",
      "decorate_frame_back_dialog.description": "If you go back now, changes will be lost.",
      "decorate_frame_back_dialog.button01": "Delete",
      "decorate_frame_back_dialog.button02": "Continue",
      "decorate_frame_confirm_dialog.warning": "Wait!",
      "decorate_frame_confirm_dialog.title": "Printing will begin right after this step.",
      "decorate_frame_confirm_dialog.description": "Make sure you are near the printer. We are not responsible for any loss caused by delayed pickup.",
      "decorate_frame_confirm_dialog.button01": "Go Back",
      "decorate_frame_confirm_dialog.button02": "Proceed",
      "decorate_frame_complete_dialog.title": "Registration Complete!\nQueue Number: @waitCount",
      "decorate_frame_complete_dialog.button01": "View History",
      "decorate_frame_complete_dialog.button02": "Go to Event Page",
      "loading.overlay01": "Rotating image properly...",
      "loading.overlay02": "Resizing image...",
      "loading.overlay03": "Merging image...",
      "loading.overlay04": "Merging all images...",
      "loading.overlay05": "Sending print request...",
      "share.button": "Share Link",
      "share.toast.event_not_found": "Failed to load event information.",
      "login.title": "Quick Login / Sign Up",
      "login.button": "Continue with @platform",
      "login.toast.exist_email": "This email is already registered.",
      "login.toast.withdrawal": "This account has been withdrawn. You can re-register after 3 months.",
      "login.toast.kakao_error01": "An error occurred during Kakao login.",
      "login.toast.kakao_error02": "Failed to retrieve Kakao account info.",
      "my_page.seeya_user": "[@name]",
      "my_page.no_name_user": "[Seeya Guest @user_id]",
      "my_page.login_from": "Logged in with @platform",
      "my_page.seeya_guide_menu": "Seeya Guide",
      "my_page.print_history": "Print History",
      "my_page.report": "Error Report",
      "my_page.qna_menu": "FAQ",
      "my_page.setting": "Settings",
      "my_page.logout": "Logout",
      "seeya_guide.title": "Seeya Guide",
      "seeya_guide.description": "A photobooth in your hand, Seeya",
      "seeya_guide.step1_title": "Find",
      "seeya_guide.step1_description": "Discover frames from special places\nin \'Seeya\'!",
      "seeya_guide.step2_title": "Capture",
      "seeya_guide.step2_description": "Fill the frame with moments you want to remember!",
      "seeya_guide.step3_title": "Print",
      "seeya_guide.step3_description": "After payment, your precious moment\nwill be printed and ready in no time!",
      "print_history.title": "Print History",
      "print_history.empty": "No history available.",
      "report.title": "Error Report",
      "report.tab_bar_menu1": "Usage History",
      "report.tab_bar_menu2": "Inquiry History",
      "report.item_button01": "Report Error",
      "report.item_button02": "Reprint",
      "report.item_status_completed": "Completed",
      "report.item_status_error": "Error",
      "report.item_status_reported": "Reported",
      "report.item_status_pending": "Printing",
      "report.item_status_wait": "Waiting",
      "report.toast.all_consumed": "You\'ve used all your reprint chances.",
      "report.toast.cant_use": "Service currently unavailable. Please try again later.",
      "report.toast.already_finish": "This event has already ended.",
      "report.toast.already_printing": "Already printing.",
      "report.toast.fail_load_user": "Failed to load user information.",
      "report_reprint_dialog.title": "Reprint",
      "report_reprint_dialog.sub_title": "Only one reprint is allowed.",
      "report_reprint_dialog.button01": "Cancel",
      "report_reprint_dialog.button02": "Print",
      "inquiry_detail.title": "Inquiry Details",
      "inquiry_detail.error_reception": "Error Reported",
      "inquiry_detail.in_progress": "In Progress",
      "inquiry_detail.status": "Status",
      "inquiry_detail.answer_pending": "We are processing your request. Please wait a moment.",
      "inquiry_detail.answer_accepted": "@date\nRefund completed.",
      "inquiry_detail.status_pending": "Refund Completed",
      "inquiry_detail.status_pending_with_date": "@date Refund Requested",
      "inquiry_detail.status_accepted": "Refund Completed",
      "inquiry_detail.status_accepted_with_date": "@date Refund Completed",
      "inquiry_detail.status_denied": "Refund Denied",
      "inquiry_detail.status_denied_with_date": "@date Refund Denied",
      "inquiry_detail.status_in_progress": "In Progress",
      "inquiry_history.print_complete": "@date Printed",
      "usage_history.report": "Report Error",
      "usage_history.reprint": "Reprint",
      "error_report.title": "Error Report",
      "error_report.cancel": "Cancel",
      "error_report.register": "Submit",
      "error_report.error_reason_title": "Describe the issue or upload a photo of the frame",
      "error_report.upload_photo": "Attach Photo",
      "error_report.toast.already_post": "Inquiry already submitted.",
      "report_complete_dialog.title": "Submission Complete!\nQueue Number: @waitCount",
      "report_complete_dialog.button01": "OK",
      "qna.title": "Frequently Asked Questions",
      "qna.footer": "For other inquiries,\nplease contact us at info@seeya-printer.com",
      "withdrawal.title": "Withdraw Membership",
      "withdrawal.sub_title": "Important Notes",
      "withdrawal.description01": "You cannot withdraw if you have ongoing or reserved events.",
      "withdrawal.description02": "Purchase history, print records, and inquiries will be permanently deleted and cannot be recovered.",
      "withdrawal.description03": "Deleted data cannot be restored even if you re-register.",
      "withdrawal.description04": "Unfinished refund requests cannot be processed.",
      "withdrawal.confirm": "I have reviewed all of the above.",
      "withdrawal.button": "Withdraw",
      "setting.title": "Settings",
      "setting.user_info_title": "Basic Info",
      "setting.user_info_name": "Name",
      "setting.user_info_phone": "Phone Number",
      "setting.user_info_phone_verify": "Verify Phone",
      "setting.user_info_email": "Email",
      "setting.sns_title": "Connected SNS",
      "setting.terms_service": "Terms of Service",
      "setting.terms_privacy": "Privacy Policy",
      "setting.withdrawal": "Withdraw Membership",
      "block.title": "You have been blocked by the administrator.",
      "payment.title": "Payment in progress.\nPlease complete it on the web.",
      "payment.toast.not_enable": "This service is currently unavailable. Please contact the administrator.",
      "maintenance.title": "Service Under Maintenance",
      "maintenance.description": "We are currently performing maintenance\nfor a safer service."
    },

    ////////////////    ////////////////    ////////////////    ////////////////    ////////////////    ////////////////    ////////////////

    'ja_JP': {
      'toast.unknown_error': '不明なエラーが発生しました。再試行してください。',
      'toast.error404': 'リクエストされたリソースが見つかりません。',
      'toast.error500': '処理中にエラーが発生しました。',
      'enter_user_info.bottom_button': '完了',
      'enter_user_info.title': '必須情報の入力',
      'enter_user_info.name': '名前',
      'enter_user_info.name_hint': '名前を入力してください',
      'enter_user_info.email': 'メールアドレス',
      'enter_user_info.email_hint': 'メールアドレス',
      'enter_user_info.email_check': '確認',
      'enter_user_info.email_check_already': 'このメールアドレスは既に使用されています。',
      'enter_user_info.email_check_okay': '使用可能なメールアドレスです。',
      'enter_user_info.toast.invalid_email': '無効なメールアドレスです。',

      'phone_verification.bottom_button_next': '次へ',
      'phone_verification.bottom_button_get_code': '認証コードを受け取る',
      'phone_verification.title': '本人確認',
      'phone_verification.sub_title': 'サービスを円滑にご利用いただくために、\n携帯電話番号を入力してください。',
      'phone_verification.phone': '携帯電話番号',
      'phone_verification.phone_hint': 'ハイフンなしで入力してください。',
      'phone_verification.code': '認証コード',
      'phone_verification.code_hint': '6桁の認証コード',
      'phone_verification.code_resend': '認証コードを再送',
      'phone_verification.toast.recaptcha': 'reCAPTCHA認証に失敗しました。',
      'phone_verification.toast.invalid_phone': '無効な電話番号です。',
      'phone_verification.toast.quota': '本日の認証リクエストの上限を超えました。後でもう一度お試しください。',
      'phone_verification.toast.error': '認証に失敗しました。',
      'phone_verification.toast.invalid_code': '認証コードを再確認してください。',
      'phone_verification.toast.code_expired': '認証コードの入力時間が切れました。',
      'phone_verification.toast.code_expired_retry': '認証時間が切れました。再度お試しください。',
      'phone_verification.toast.too_many': 'リクエストが多すぎます。しばらくしてから再度お試しください。',
      'phone_verification.toast.network': 'ネットワーク接続に問題が発生しました。',
      'phone_verification.toast.code_short': '6桁すべての認証コードを入力してください。',

      "sign_up_finish.bottom_button": "はじめる",
      "sign_up_finish.title": "会員登録が\n完了しました！",
      "sign_up_finish.sub_title": "ようこそ、@user さん！",
      "bottom_nav.home": "ホーム",
      "bottom_nav.map": "マップ",
      "bottom_nav.my_page": "マイページ",
      "home.detail_dialog_button": "イベント詳細を見る",
      "map.search_hint": "場所やイベント名で検索",
      "map.event_list_title": "おすすめのイベント",
      "map.event_list_empty": "開催中のイベントがありません。",
      "map.event_list_item_period": "期間 @start_date - @end_date",
      "map.toast.location_error": "位置情報を取得できません。位置情報の許可をご確認ください。",
      "map_sort.title": "並び替え",
      "map_sort.popular": "人気順",
      "map_sort.distance": "距離順",
      "map_sort.unknown": "不明",
      "search.bar_hint": "場所やイベント名で検索",
      "search.recent": "最近の検索",
      "search.clear": "すべて削除",
      "event_detail.price": "プリント料金",
      "event_detail.period": "開催期間",
      "event_detail.address": "住所",
      "event_detail.address_copy": "住所をコピー",
      "event_detail.frame_list_title": "フレームを選択してください",
      "event_detail.frame_list_empty": "このイベントは終了しました。",
      "event_detail.toast.load_fail": "イベント情報の読み込みに失敗しました。",
      "event_detail.toast.copied": "コピーしました。",
      "camera.complete": "完了",
      "camera.delete": "削除",
      "camera.toast.allow_permission": "カメラのアクセス許可を有効にしてください。",
      "camera.toast.init_error": "カメラの初期化中にエラーが発生しました。",
      "image_crop.button": "切り取り",
      "image_crop.toast.size_error": "画像サイズの取得に失敗しました。",
      "decorate_frame.title": "フレーム内をデコレーション",
      "decorate_frame.button": "プリント",
      "decorate_frame.toast.empty_cut": "すべてのカットを埋めてください！",
      "decorate_frame.toast.not_found_user": "ユーザー情報の取得に失敗しました。",
      "decorate_frame.toast.all_consumed": "再印刷回数をすべて使用しました。",
      "decorate_frame.toast.cant_user": "現在サービスをご利用いただけません。しばらくしてから再度お試しください。",
      "decorate_frame.toast.already_finish": "このイベントは終了しています。",
      "decorate_frame.toast.already_printing": "すでに印刷が進行中です。",
      "decorate_frame.toast.merge_error": "画像の結合中にエラーが発生しました。",
      "decorate_frame_back_dialog.title": "このフレームを削除しますか？",
      "decorate_frame_back_dialog.description": "戻ると編集内容は破棄されます。",
      "decorate_frame_back_dialog.button01": "削除する",
      "decorate_frame_back_dialog.button02": "編集を続ける",
      "decorate_frame_confirm_dialog.warning": "ちょっと待って！",
      "decorate_frame_confirm_dialog.title": "この次のステップで\nすぐに印刷が始まります。",
      "decorate_frame_confirm_dialog.description": "プリンターのそばでお待ちください。受け取りの遅れによる紛失には責任を負いかねます。",
      "decorate_frame_confirm_dialog.button01": "戻る",
      "decorate_frame_confirm_dialog.button02": "進む",
      "decorate_frame_complete_dialog.title": "登録が完了しました！\n受付番号：@waitCount",
      "decorate_frame_complete_dialog.button01": "マイプリントを見る",
      "decorate_frame_complete_dialog.button02": "イベントページへ",
      "loading.overlay01": "画像を回転中...",
      "loading.overlay02": "画像をリサイズ中...",
      "loading.overlay03": "画像を結合中...",
      "loading.overlay04": "すべての画像を結合中...",
      "loading.overlay05": "印刷リクエストを送信中...",
      "share.button": "リンクを共有",
      "share.toast.event_not_found": "イベント情報の読み込みに失敗しました。",
      "login.title": "簡単ログイン / 会員登録",
      "login.button": "@platform で続ける",
      "login.toast.exist_email": "このメールアドレスはすでに登録されています。",
      "login.toast.withdrawal": "このアカウントは退会済みです。再登録は3ヶ月後に可能です。",
      "login.toast.kakao_error01": "Kakaoログイン中にエラーが発生しました。",
      "login.toast.kakao_error02": "Kakaoアカウント情報の取得に失敗しました。",
      "my_page.seeya_user": "[@name]",
      "my_page.no_name_user": "[Seeyaゲスト @user_id]",
      "my_page.login_from": "@platform でログイン中",
      "my_page.seeya_guide_menu": "Seeyaとは",
      "my_page.print_history": "プリント履歴",
      "my_page.report": "エラー報告",
      "my_page.qna_menu": "よくある質問",
      "my_page.setting": "設定",
      "my_page.logout": "ログアウト",
      "seeya_guide.title": "Seeyaとは",
      "seeya_guide.description": "手のひらフォトブース、Seeya",
      "seeya_guide.step1_title": "探す",
      "seeya_guide.step1_description": "Seeyaで特別な場所の\nフレームを探そう！",
      "seeya_guide.step2_title": "撮る",
      "seeya_guide.step2_description": "選んだフレームで\n思い出を撮ろう！",
      "seeya_guide.step3_title": "プリント",
      "seeya_guide.step3_description": "決済完了後、少し待つだけで\nあなたの特別な瞬間が手元に！",
      "print_history.title": "プリント履歴",
      "print_history.empty": "履歴がありません。",
      "report.title": "エラー報告",
      "report.tab_bar_menu1": "使用履歴",
      "report.tab_bar_menu2": "お問い合わせ",
      "report.item_button01": "エラー報告",
      "report.item_button02": "再印刷",
      "report.item_status_completed": "印刷完了",
      "report.item_status_error": "エラー",
      "report.item_status_reported": "お問い合わせ済み",
      "report.item_status_pending": "印刷中",
      "report.item_status_wait": "待機中",
      "report.toast.all_consumed": "再印刷回数をすべて使用しました。",
      "report.toast.cant_use": "現在サービスをご利用いただけません。しばらくしてから再度お試しください。",
      "report.toast.already_finish": "このイベントは終了しています。",
      "report.toast.already_printing": "すでに印刷が進行中です。",
      "report.toast.fail_load_user": "ユーザー情報の取得に失敗しました。",
      "report_reprint_dialog.title": "再印刷",
      "report_reprint_dialog.sub_title": "再印刷は1回のみ可能です。",
      "report_reprint_dialog.button01": "キャンセル",
      "report_reprint_dialog.button02": "印刷する",
      "inquiry_detail.title": "お問い合わせ履歴",
      "inquiry_detail.error_reception": "エラー受付",
      "inquiry_detail.in_progress": "対応中",
      "inquiry_detail.status": "ステータス",
      "inquiry_detail.answer_pending": "現在対応中です。しばらくお待ちください。",
      "inquiry_detail.answer_accepted": "@date\n返金完了",
      "inquiry_detail.status_pending": "返金完了",
      "inquiry_detail.status_pending_with_date": "@date 返金申請",
      "inquiry_detail.status_accepted": "返金完了",
      "inquiry_detail.status_accepted_with_date": "@date 返金完了",
      "inquiry_detail.status_denied": "返金不可",
      "inquiry_detail.status_denied_with_date": "@date 返金不可",
      "inquiry_detail.status_in_progress": "対応中",
      "inquiry_history.print_complete": "@date 印刷完了",
      "usage_history.report": "エラー報告",
      "usage_history.reprint": "再印刷",
      "error_report.title": "エラー報告",
      "error_report.cancel": "キャンセル",
      "error_report.register": "送信",
      "error_report.error_reason_title": "問題の内容とフレームの写真を添付してください。",
      "error_report.upload_photo": "写真を添付",
      "error_report.toast.already_post": "すでにお問い合わせが送信されています。",
      "report_complete_dialog.title": "受付が完了しました！\n受付番号：@waitCount",
      "report_complete_dialog.button01": "確認",
      "qna.title": "よくある質問",
      "qna.footer": "その他のお問い合わせは、\nサポートチーム（info@seeya-printer.com）までご連絡ください。",
      "withdrawal.title": "アカウント削除",
      "withdrawal.sub_title": "削除前にご確認ください",
      "withdrawal.description01": "現在進行中または予定中のイベントがある場合、アカウントを削除できません。",
      "withdrawal.description02": "購入履歴、プリント履歴、お問い合わせ履歴はすべて削除され、復元できません。",
      "withdrawal.description03": "退会後、再登録してもデータは復元されません。",
      "withdrawal.description04": "返金申請中の内容は処理されません。",
      "withdrawal.confirm": "上記の内容を確認しました。",
      "withdrawal.button": "アカウントを削除する",
      "setting.title": "設定",
      "setting.user_info_title": "基本情報",
      "setting.user_info_name": "名前",
      "setting.user_info_phone": "電話番号",
      "setting.user_info_phone_verify": "電話番号を認証",
      "setting.user_info_email": "メールアドレス",
      "setting.sns_title": "SNS連携",
      "setting.terms_service": "利用規約",
      "setting.terms_privacy": "プライバシーポリシー",
      "setting.withdrawal": "アカウント削除",
      "block.title": "管理者によりブロックされています。",
      "payment.title": "お支払い中です。\nWebで決済を完了してください！",
      "payment.toast.not_enable": "サービスを利用できません。サポートまでご連絡ください。",
      "maintenance.title": "メンテナンス中",
      "maintenance.description": "安全でスムーズなサービス提供のため、\n現在メンテナンスを実施中です。"
    },
  };



}